services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    restart: unless-stopped
    env_file: ./docker.env
    extra_hosts:                          
      - "smtp.sendgrid.net:52.204.68.213" 
    ports:
      - "3000:3000"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis
    restart: unless-stopped
    env_file: ./docker.env
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file: ./docker.env
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "amcmorrow84"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'amcmorrow84'
      POSTGRES_PASSWORD: 'McMorrow!984'
      POSTGRES_DB: 'outline'

volumes:
  storage-data:
  database-data: